const axios = require('axios');
const fs = require('fs');
const path = require('path');

// NVIDIA API Configuration
const NVIDIA_API_BASE = 'https://integrate.api.nvidia.com/v1';
const NVIDIA_MODEL = process.env.NVIDIA_TEXT_MODEL || 'nvidia/nemotron-3-super-120b-a12b';

// File paths
const TOPICS_FILE = path.join(__dirname, '..', 'topics.json');
const GENERATED_TOPICS_FILE = path.join(__dirname, '..', 'generated-topics.json');
const GUIDES_DIR = path.join(__dirname, '..', '_guides');
const IMAGES_DIR = path.join(__dirname, '..', 'assets', 'images', 'guides');

const IMAGE_MODELS = [
  {
    key: 'dev',
    name: 'FLUX.1-dev',
    url: 'https://ai.api.nvidia.com/v1/genai/black-forest-labs/flux.1-dev',
    steps: 50,
    retries: 2,
    timeoutMs: 600000,
    credit: 'Generated by NVIDIA FLUX.1-dev',
    credit_url: 'https://build.nvidia.com/black-forest-labs/flux_1-dev'
  },
  {
    key: 'klein',
    name: 'FLUX.2-klein-4b',
    url: 'https://ai.api.nvidia.com/v1/genai/black-forest-labs/flux.2-klein-4b',
    steps: 4,
    retries: 3,
    timeoutMs: 300000,
    credit: 'Generated by NVIDIA FLUX.2-klein-4b',
    credit_url: 'https://build.nvidia.com/black-forest-labs/flux_2-klein-4b'
  },
  {
    key: 'schnell',
    name: 'FLUX.1-schnell',
    url: 'https://ai.api.nvidia.com/v1/genai/black-forest-labs/flux.1-schnell',
    steps: 4,
    retries: 3,
    timeoutMs: 300000,
    credit: 'Generated by NVIDIA FLUX.1-schnell',
    credit_url: 'https://build.nvidia.com/black-forest-labs/flux_1-schnell'
  }
];

// Ensure directories exist
if (!fs.existsSync(GUIDES_DIR)) {
  fs.mkdirSync(GUIDES_DIR, { recursive: true });
}
if (!fs.existsSync(IMAGES_DIR)) {
  fs.mkdirSync(IMAGES_DIR, { recursive: true });
}

// Read topics and generated topics
function loadTopics() {
  const topics = JSON.parse(fs.readFileSync(TOPICS_FILE, 'utf-8'));
  const generatedTopics = JSON.parse(fs.readFileSync(GENERATED_TOPICS_FILE, 'utf-8'));
  return { topics, generatedTopics };
}

// Save generated topics
function saveGeneratedTopics(generatedTopics) {
  fs.writeFileSync(GENERATED_TOPICS_FILE, JSON.stringify(generatedTopics, null, 2));
}

// Helper: Convert title to slug format for comparison
function titleToSlug(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

// Select next topic with smart series prioritization
// Priority order:
//   1. Continue in-progress series (previous part published)
//   2. Start beginner-friendly series (part 1, difficulty: beginner)
//   3. Start any series (part 1)
//   4. Any series topic
//   5. Random standalone topic
function selectNextTopic(topics, generatedTopics) {
  const unusedTopics = topics.filter(
    topic => !generatedTopics.includes(topic.title)
  );

  if (unusedTopics.length === 0) {
    // All topics used, reset and start over
    console.log('All topics have been used. Resetting...');
    return topics[Math.floor(Math.random() * topics.length)];
  }

  // Convert generated topics to slug format for matching
  const generatedSlugs = generatedTopics.map(titleToSlug);

  // PRIORITY 1: Complete in-progress series (previous part already published)
  const continueSeriesTopics = unusedTopics.filter(topic => {
    if (!topic.series || !topic.series.previous) return false;

    // Check if the previous part has been generated
    const previousSlug = topic.series.previous;
    const previousPublished = generatedSlugs.some(slug => slug === previousSlug);

    return previousPublished;
  });

  if (continueSeriesTopics.length > 0) {
    // Sort by series part number to maintain order
    continueSeriesTopics.sort((a, b) => {
      if (a.series.name === b.series.name) {
        return a.series.part - b.series.part;
      }
      return 0;
    });

    const selected = continueSeriesTopics[0];
    console.log(`📚 Continuing series: "${selected.series.name}" (Part ${selected.series.part}/${selected.series.total})`);
    return selected;
  }

  // PRIORITY 2: Start beginner-friendly series
  const beginnerSeriesStarts = unusedTopics.filter(topic =>
    topic.series &&
    topic.series.part === 1 &&
    topic.difficulty === 'beginner'
  );

  if (beginnerSeriesStarts.length > 0) {
    const selected = beginnerSeriesStarts[Math.floor(Math.random() * beginnerSeriesStarts.length)];
    console.log(`🌟 Starting beginner series: "${selected.series.name}"`);
    return selected;
  }

  // PRIORITY 3: Start any series
  const seriesStarts = unusedTopics.filter(topic =>
    topic.series && topic.series.part === 1
  );

  if (seriesStarts.length > 0) {
    const selected = seriesStarts[Math.floor(Math.random() * seriesStarts.length)];
    console.log(`📖 Starting series: "${selected.series.name}"`);
    return selected;
  }

  // REMOVED PRIORITY 4: Do NOT allow generating series parts out of order
  // Series topics can ONLY be generated if they are part 1 OR if the previous part exists
  // This ensures series are always authored sequentially

  // FALLBACK: Random standalone topic
  const selected = unusedTopics[Math.floor(Math.random() * unusedTopics.length)];
  console.log(`📄 Generating standalone topic`);
  return selected;
}

// Validate a URL by checking if it returns a successful response
async function validateUrl(url, timeout = 10000) {
  try {
    const response = await axios.head(url, {
      timeout,
      maxRedirects: 5,
      validateStatus: (status) => status >= 200 && status < 400
    });
    return true;
  } catch (error) {
    // Try GET if HEAD fails (some servers don't support HEAD)
    try {
      const response = await axios.get(url, {
        timeout,
        maxRedirects: 5,
        validateStatus: (status) => status >= 200 && status < 400,
        responseType: 'stream'
      });
      // Cancel the stream immediately, we just need to check if it's accessible
      response.data.destroy();
      return true;
    } catch (getError) {
      console.log(`  ✗ Invalid URL: ${url} (${getError.message})`);
      return false;
    }
  }
}

// Extract and validate URLs from markdown content
async function validateLinksInContent(content) {
  // Match markdown links: [text](url)
  const linkRegex = /\[([^\]]+)\]\(([^)]+)\)/g;
  const matches = [...content.matchAll(linkRegex)];

  if (matches.length === 0) {
    return content;
  }

  console.log(`Validating ${matches.length} links...`);

  const validatedLinks = await Promise.all(
    matches.map(async (match) => {
      const fullMatch = match[0];
      const text = match[1];
      const url = match[2];

      // Skip internal links (starting with /)
      if (url.startsWith('/') || url.startsWith('#')) {
        return { fullMatch, isValid: true };
      }

      const isValid = await validateUrl(url);
      if (isValid) {
        console.log(`  ✓ Valid: ${url}`);
      }

      return { fullMatch, isValid };
    })
  );

  // Remove invalid links from content
  let validatedContent = content;
  validatedLinks.forEach(({ fullMatch, isValid }) => {
    if (!isValid) {
      // Remove the entire line containing the invalid link
      const lines = validatedContent.split('\n');
      validatedContent = lines
        .filter(line => !line.includes(fullMatch))
        .join('\n');
    }
  });

  const removedCount = validatedLinks.filter(l => !l.isValid).length;
  if (removedCount > 0) {
    console.log(`Removed ${removedCount} invalid link(s)`);
  }

  return validatedContent;
}

// Helper function to detect transient errors that should be retried
function isTransientError(error) {
  // Check for HTTP status codes indicating transient issues
  if (error.response) {
    const status = error.response.status;
    if (status === 502 || status === 503 || status === 504) {
      return true;
    }
  }

  // Check for network errors
  if (error.code) {
    const transientCodes = ['ECONNRESET', 'ETIMEDOUT', 'ECONNREFUSED', 'ENETUNREACH', 'ECONNABORTED', 'EAI_AGAIN', 'ENOTFOUND', 'ESOCKETTIMEDOUT'];
    if (transientCodes.includes(error.code)) {
      return true;
    }
  }

  if (error.message && /timeout|socket hang up|network/i.test(error.message)) {
    return true;
  }

  return false;
}

// Generate guide content with retry logic for transient errors
async function generateGuideContentWithRetry(topic, maxRetries = 3) {
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      console.log(`  Text generation attempt ${attempt}/${maxRetries}...`);

      // Add series context if this is part of a series
      let seriesContext = '';
      if (topic.series) {
        seriesContext = `
SERIES CONTEXT:
This guide is part ${topic.series.part} of ${topic.series.total} in the "${topic.series.name}" series.`;

        if (topic.series.previous) {
          seriesContext += `\nPrevious guide: "${topic.series.previous.replace(/-/g, ' ')}"`;
        }
        if (topic.series.next) {
          seriesContext += `\nNext guide: "${topic.series.next.replace(/-/g, ' ')}"`;
        }

        seriesContext += `\n- Assume readers may have completed previous parts if applicable
- Build on concepts from earlier parts naturally
- Reference previous parts when helpful but don't require them
- Make this guide valuable both standalone AND as part of the series
`;
      }

      const prompt = `Create a Scripture-grounded article about "${topic.title}" for decent.church.
${seriesContext}
MISSION AND THEOLOGICAL POSTURE:
- Write from a broadly Judeo-Christian perspective centered on loving God and loving neighbor.
- Be welcoming to seekers, returning believers, lifelong Christians, and people carrying questions or church hurt.
- Ground counsel in Scripture, especially the teaching of Jesus, wisdom literature, prophets, apostles, and the great commandments.
- Use NIV as the Scripture reference basis. Prefer references and brief excerpts over long quotations.
- Include this note when quoting Scripture: Scripture quotations are from the New International Version (NIV).
- Avoid partisan politics, denominational scorekeeping, culture-war framing, and claims that one tradition alone represents the whole church.
- Be pastoral and practical. Do not shame readers. Invite them toward faith, wisdom, community, repentance, mercy, and hope.

WRITING STYLE:
- Conversational, gentle, clear, and mature.
- Use "we" more than "you" when naming common struggles.
- Avoid hype, sarcasm, and insider jargon.
- Do not use emojis anywhere.
- Appropriate for ${topic.difficulty} level readers.

VISUAL FORMATTING RULES:
- Do not use emojis in titles, headings, callouts, lists, or body copy.
- Use Markdown only.
- Use blockquote syntax for callout boxes. Each callout must start with >.
- Callout examples:
  > **Pastoral Note:** A short word of encouragement.

  > **Scripture Reflection:** A brief reflection connected to a Bible reference.

  > **Practice:** A concrete step the reader can try this week.
- Use **bold** sparingly for emphasis.
- Section headers must use ##.

ARTICLE STRUCTURE:
1. First line: the article title in bold only, with no emoji.
2. Second line: equals signs, minimum 50 characters.
3. Introduction: 2-3 warm sentences naming why this matters.
4. ## Scripture Foundation
   - Include 2-4 NIV references, with short quoted excerpts only when useful.
   - Explain how the passages guide the topic.
5. ## What This Looks Like in Daily Life
   - Give practical, concrete examples.
6. ## Questions for Reflection
   - Include 4-6 thoughtful questions.
7. ## A Simple Practice This Week
   - Include one doable practice and one gentle next step.
8. ## Prayer
   - Write a short original prayer. Do not imitate a copyrighted prayer.
9. ## Key Takeaways
   - Use concise bullet points.
10. ## Further Reading
   - Prefer Scripture references and stable, real resources.
   - Include 2-3 real links where possible, but do not invent URLs.

HEADER FORMAT:
- Correct title format:
  **How to Begin Looking for a Church Family**
  ====================================================================

FURTHER READING FORMAT:
- [Resource Title](https://actual-url.com) - Brief description
- Scripture: Matthew 22:37-40; Micah 6:8; Hebrews 10:24-25

Write only the Markdown article body. Do not include YAML front matter.`;

      const response = await axios.post(
        `${NVIDIA_API_BASE}/chat/completions`,
        {
          model: NVIDIA_MODEL,
          messages: [
            {
              role: 'user',
              content: prompt
            }
          ],
          temperature: 0.7,
          top_p: 1,
          max_tokens: 5000,
          stream: false
        },
        {
          headers: {
            'Authorization': `Bearer ${process.env.NVIDIA_API_KEY}`,
            'Content-Type': 'application/json'
          },
          timeout: 240000 // 4 minute timeout for slower text-generation responses
        }
      );

      let content = response.data.choices[0].message.content;

      // Strip thinking tokens emitted by reasoning models (e.g. Nemotron)
      content = content.replace(/<think>[\s\S]*?<\/think>\s*/g, '').trimStart();

      // Validate all links in the generated content
      const validatedContent = await validateLinksInContent(content);

      console.log('  ✓ Text generation successful');
      return validatedContent;

    } catch (error) {
      const isTransient = isTransientError(error);
      const errorMsg = error.response?.data?.message || error.message;
      const statusCode = error.response?.status || error.code;

      console.error(`  ✗ Attempt ${attempt} failed: ${statusCode} - ${errorMsg}`);

      // If it's a transient error and we have retries left, wait and retry
      if (isTransient && attempt < maxRetries) {
        const waitTime = Math.pow(2, attempt) * 15000; // 30s, 60s, 120s
        console.log(`  Transient error detected. Waiting ${waitTime/1000}s before retry...`);
        await new Promise(resolve => setTimeout(resolve, waitTime));
      } else {
        // Non-transient error or out of retries - throw a concise error for CI logs
        const apiDetails = error.response?.data ? JSON.stringify(error.response.data) : error.message;
        console.error('NVIDIA API Error:', apiDetails);
        throw new Error(`Text generation failed after ${attempt} attempt(s): ${statusCode} - ${errorMsg}`);
      }
    }
  }

  throw new Error('Text generation failed after all retry attempts');
}

// Backward compatibility wrapper
async function generateGuideContent(topic) {
  return generateGuideContentWithRetry(topic);
}

// Find related guides based on shared tags
function findRelatedGuides(topic, maxRelated = 3) {
  try {
    const guides = fs.readdirSync(GUIDES_DIR)
      .filter(file => file.endsWith('.md'))
      .map(file => {
        const content = fs.readFileSync(path.join(GUIDES_DIR, file), 'utf-8');
        const frontMatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
        if (!frontMatterMatch) return null;

        const frontMatter = frontMatterMatch[1];
        const titleMatch = frontMatter.match(/title:\s*"(.+?)"/);
        const tagsMatch = frontMatter.match(/tags:\s*\[(.*?)\]/);

        if (!titleMatch) return null;

        const title = titleMatch[1];
        const tags = tagsMatch ? tagsMatch[1].split(',').map(t => t.trim().replace(/"/g, '')) : [];

        return { title, tags, file };
      })
      .filter(guide => guide !== null);

    // Calculate relevance score based on shared tags
    const scoredGuides = guides
      .map(guide => {
        const sharedTags = guide.tags.filter(tag => topic.tags.includes(tag));
        return {
          ...guide,
          score: sharedTags.length
        };
      })
      .filter(guide => guide.score > 0 && guide.title !== topic.title)
      .sort((a, b) => b.score - a.score)
      .slice(0, maxRelated);

    return scoredGuides.map(guide => ({
      title: guide.title,
      url: `/guides/${guide.file.replace(/^\d{4}-\d{2}-\d{2}-/, '').replace(/\.md$/, '')}/`
    }));
  } catch (error) {
    console.error('Error finding related guides:', error.message);
    return [];
  }
}

// Create filename from title
function createFilename(title) {
  const date = new Date().toISOString().split('T')[0];
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  return `${date}-${slug}.md`;
}

// Generate guide description from title
function generateDescription(title, difficulty) {
  const starters = {
    beginner: 'A welcoming guide to',
    intermediate: 'A practical reflection on',
    advanced: 'A deeper scriptural look at'
  };
  return `${starters[difficulty]} ${title.toLowerCase()}`;
}

// Generate article image prompt from topic
function generateImagePrompt(topic) {
  const keywords = topic.tags.slice(0, 3).join(', ');

  return {
    prompt: `Mosaic illustration for a Scripture-grounded article about ${topic.title}. Create a biblical-looking landscape connected to ${keywords}: desert paths, hills, olive trees, rivers, still waters, gardens, fields, shepherding country, ancient stone roads, dawn light, simple wooden cups, bread, fish, vines, or peaceful wilderness. Use hand-laid mosaic tile texture, earthy natural colors, subtle gold and blue accents, ancient Near Eastern landscape atmosphere, reverent and peaceful composition, no people, no faces, no readable text, no letters, no watermark, no logo, no denominational branding`,
    negative_prompt: `people, person, human figure, faces, portraits, hands, crowds, text, letters, words, typography, watermark, logo, denomination symbols, political signs, photorealistic people, stained glass, lead came, window panes`
  };
}

// Helper function to try generating image with a specific FLUX model
async function tryGenerateWithModel(promptData, modelUrl, modelName, steps, maxRetries = 3, timeoutMs = 300000) {
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    let requestBody;

    try {
      console.log(`Attempt ${attempt}/${maxRetries}: Sending prompt to ${modelName}...`);

      requestBody = {
        prompt: promptData.prompt,
        width: 1024,
        height: 1024,
        seed: Math.floor(Math.random() * 1000000),
        steps: steps
      };

      // Note: Negative prompt may not be supported by NVIDIA FLUX API
      // Commenting out for now to avoid 422 errors
      // if (promptData.negative_prompt && modelName.includes('dev')) {
      //   requestBody.negative_prompt = promptData.negative_prompt;
      // }

      const response = await axios.post(
        modelUrl,
        requestBody,
        {
          headers: {
            'Authorization': `Bearer ${process.env.NVIDIA_API_KEY}`,
            'Content-Type': 'application/json',
            'Accept': 'application/json'
          },
          timeout: timeoutMs
        }
      );

      // Extract image data from response
      if (!response.data || !response.data.artifacts || response.data.artifacts.length === 0) {
        throw new Error('No image data in response');
      }

      const artifact = response.data.artifacts[0];
      if (artifact.finishReason !== 'SUCCESS') {
        throw new Error(`Image generation failed: ${artifact.finishReason}`);
      }

      console.log(`✓ Success! Image generated with ${modelName}`);
      return artifact.base64;

    } catch (error) {
      const isTimeout = error.code === 'ECONNABORTED' || error.message.includes('timeout');
      const isServerError = error.response && error.response.status >= 500;

      console.error(`✗ Attempt ${attempt} failed: ${error.message}`);

      if (error.response) {
        console.error(`   HTTP Status: ${error.response.status}`);
        if (error.response.data) {
          console.error(`   API Response:`, JSON.stringify(error.response.data));
        }
        if (error.response.headers) {
          console.error(`   Response Headers:`, JSON.stringify(error.response.headers));
        }
      }

      // Log request details for debugging
      if (attempt === maxRetries) {
        console.error(`   Request URL: ${modelUrl}`);
        console.error(`   Request Body:`, JSON.stringify(requestBody, null, 2));
      }

      if (isTimeout) {
        console.error(`   (Request timed out after ${timeoutMs/1000}s - API may be overloaded)`);
      } else if (isServerError) {
        console.error(`   (Server error - NVIDIA API may be experiencing issues)`);
      }

      // Don't retry immediately on server errors - wait longer
      if (attempt < maxRetries) {
        const waitTime = isServerError ?
          Math.pow(2, attempt) * 15000 : // 30s, 60s for server errors
          Math.pow(2, attempt) * 10000;   // 20s, 40s for other errors
        console.log(`   Waiting ${waitTime/1000}s before retry...`);
        await new Promise(resolve => setTimeout(resolve, waitTime));
      }
    }
  }

  return null;
}

// Generate and save image using NVIDIA's FLUX models with fallback
async function fetchAndSaveImage(topic) {
  const slug = topic.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  const filename = `${slug}.jpg`;
  const filepath = path.join(IMAGES_DIR, filename);

  // Check if image already exists
  if (fs.existsSync(filepath)) {
    console.log(`Image already exists: ${filename}`);
    return {
      path: `/assets/images/guides/${filename}`,
      credit: IMAGE_MODELS[0].credit,
      credit_url: IMAGE_MODELS[0].credit_url
    };
  }

  console.log(`Generating AI image for: ${topic.title}`);

  const prompt = generateImagePrompt(topic);
  let imageBase64 = null;
  let modelUsed = null;

  for (const model of IMAGE_MODELS) {
    console.log(`\n🎨 Trying ${model.name}...`);
    imageBase64 = await tryGenerateWithModel(
      prompt,
      model.url,
      model.name,
      model.steps,
      model.retries,
      model.timeoutMs
    );

    if (imageBase64) {
      modelUsed = model.key;
      break;
    }

    console.log(`\n🔄 ${model.name} failed; trying next available image model...`);
  }

  // If both models failed
  if (!imageBase64) {
    console.error('\n⚠️  All attempts with both FLUX models failed.');
    console.error('    This is likely a temporary NVIDIA API issue.');
    console.error('    Guide will be created without image - you can generate the image later.');
    console.error('    To retry image generation for this guide, run:');
    console.error(`    node scripts/add-images-retroactive.js`);
    return null;
  }

  // Save the image
  const imageBuffer = Buffer.from(imageBase64, 'base64');
  fs.writeFileSync(filepath, imageBuffer);

  const creditInfo = IMAGE_MODELS.find(model => model.key === modelUsed);

  console.log(`✓ AI-generated image saved: ${filename} (using ${modelUsed})`);

  return {
    path: `/assets/images/guides/${filename}`,
    ...creditInfo
  };
}

// Create guide file
async function createGuideFile(topic, content, imageData) {
  const filename = createFilename(topic.title);
  const filepath = path.join(GUIDES_DIR, filename);

  const date = new Date().toISOString().split('T')[0];
  const description = generateDescription(topic.title, topic.difficulty);

  // Find related guides
  const relatedGuides = findRelatedGuides(topic);

  // Add related guides section if any found
  if (relatedGuides.length > 0) {
    content += `\n\n## Related Guides\n\n`;
    content += `Want to learn more? Check out these related guides:\n\n`;
    relatedGuides.forEach(guide => {
      content += `- [${guide.title}](${guide.url})\n`;
    });
  }

  // Estimate reading time (rough: 200 words per minute)
  const wordCount = content.split(/\s+/).length;
  const readingTime = Math.ceil(wordCount / 200);

  // Build front matter with optional image data and series info
  let frontMatter = `---
layout: guide
title: "${topic.title}"
date: ${date}
difficulty: ${topic.difficulty}
tags: [${topic.tags.map(tag => `"${tag}"`).join(', ')}]
description: "${description}"
estimated_time: "${readingTime} min read"`;

  if (imageData) {
    frontMatter += `
image: "${imageData.path}"
image_credit: "${imageData.credit}"
image_credit_url: "${imageData.credit_url}"`;
  }

  // Add series metadata if present
  if (topic.series) {
    frontMatter += `
series:
  name: "${topic.series.name}"
  part: ${topic.series.part}
  total: ${topic.series.total}
`;

    if (topic.series.previous) {
      frontMatter += `  previous: "${topic.series.previous}"
`;
    }
    if (topic.series.next) {
      frontMatter += `  next: "${topic.series.next}"
`;
    }
  }

  frontMatter += `
---

`;

  const fullContent = frontMatter + content;
  fs.writeFileSync(filepath, fullContent);

  console.log(`Created guide: ${filename}`);
  if (relatedGuides.length > 0) {
    console.log(`Added ${relatedGuides.length} related guide links`);
  }
  return filename;
}

// Update series navigation in all guides of the same series
function updateSeriesNavigation(newTopic) {
  if (!newTopic.series) {
    return;
  }

  console.log('\nUpdating series navigation for all guides in the series...');

  // Load topics.json to get the authoritative series structure
  const { topics } = loadTopics();

  // Find all topics in the same series
  const seriesTopics = topics.filter(t =>
    t.series && t.series.name === newTopic.series.name
  ).sort((a, b) => a.series.part - b.series.part);

  if (seriesTopics.length === 0) {
    console.log('  ⚠ No series topics found in topics.json');
    return;
  }

  console.log(`  Found ${seriesTopics.length} parts in "${newTopic.series.name}" series`);

  // Update each guide in the series to match topics.json
  seriesTopics.forEach((topic, index) => {
    const slug = titleToSlug(topic.title);
    const files = fs.readdirSync(GUIDES_DIR).filter(f => f.includes(slug));

    if (files.length === 0) {
      // Guide hasn't been created yet, skip it
      return;
    }

    const filePath = path.join(GUIDES_DIR, files[0]);
    let content = fs.readFileSync(filePath, 'utf-8');
    let modified = false;

    // Update part number if different
    const currentPartMatch = content.match(/part:\s*(\d+)/m);
    if (currentPartMatch && parseInt(currentPartMatch[1]) !== topic.series.part) {
      content = content.replace(/part:\s*\d+/m, `part: ${topic.series.part}`);
      console.log(`  ✓ Updated ${files[0]}: part ${currentPartMatch[1]} → ${topic.series.part}`);
      modified = true;
    }

    // Update total if different
    const currentTotalMatch = content.match(/total:\s*(\d+)/m);
    if (currentTotalMatch && parseInt(currentTotalMatch[1]) !== topic.series.total) {
      content = content.replace(/total:\s*\d+/m, `total: ${topic.series.total}`);
      console.log(`  ✓ Updated ${files[0]}: total ${currentTotalMatch[1]} → ${topic.series.total}`);
      modified = true;
    }

    // Update previous link
    const shouldHavePrevious = index > 0;
    const hasPreviousLink = /previous:\s*"[^"]+"/m.test(content);

    if (shouldHavePrevious) {
      const prevSlug = titleToSlug(seriesTopics[index - 1].title);
      const currentPrevMatch = content.match(/previous:\s*"([^"]+)"/m);

      // Check if previous guide actually exists
      const prevGuideExists = fs.readdirSync(GUIDES_DIR).some(f => f.includes(prevSlug));

      if (prevGuideExists) {
        if (!hasPreviousLink) {
          // Add previous link after part line
          content = content.replace(
            /(part:\s*\d+)\n/m,
            `$1\n  total: ${topic.series.total}\n  previous: "${prevSlug}"\n`
          );
          // Remove duplicate total if it exists
          content = content.replace(/total:\s*\d+\n\s*total:\s*\d+/m, (match) => {
            const totalMatch = match.match(/total:\s*(\d+)/);
            return `total: ${totalMatch[1]}`;
          });
          console.log(`  ✓ Added previous link to ${files[0]}: ${prevSlug}`);
          modified = true;
        } else if (currentPrevMatch && currentPrevMatch[1] !== prevSlug) {
          content = content.replace(/previous:\s*"[^"]+"/m, `previous: "${prevSlug}"`);
          console.log(`  ✓ Fixed previous link in ${files[0]}: ${prevSlug}`);
          modified = true;
        }
      } else if (hasPreviousLink) {
        // Remove previous link if target guide doesn't exist
        content = content.replace(/\s*previous:\s*"[^"]+"\n/m, '');
        console.log(`  ✓ Removed previous link to non-existent guide from ${files[0]}`);
        modified = true;
      }
    } else if (hasPreviousLink) {
      // Remove previous link if this is now part 1
      content = content.replace(/\s*previous:\s*"[^"]+"\n/m, '');
      console.log(`  ✓ Removed incorrect previous link from ${files[0]}`);
      modified = true;
    }

    // Update next link
    const shouldHaveNext = index < seriesTopics.length - 1;
    const hasNextLink = /next:\s*"[^"]+"/m.test(content);

    if (shouldHaveNext) {
      const nextSlug = titleToSlug(seriesTopics[index + 1].title);
      const currentNextMatch = content.match(/next:\s*"([^"]+)"/m);

      // Check if next guide actually exists
      const nextGuideExists = fs.readdirSync(GUIDES_DIR).some(f => f.includes(nextSlug));

      if (nextGuideExists) {
        if (!hasNextLink) {
          // Add next link
          const hasPreviousLine = /previous:\s*"[^"]+"/m.test(content);
          if (hasPreviousLine) {
            content = content.replace(
              /(previous:\s*"[^"]+")\n/m,
              `$1\n  next: "${nextSlug}"\n`
            );
          } else {
            content = content.replace(
              /(total:\s*\d+)\n/m,
              `$1\n  next: "${nextSlug}"\n`
            );
          }
          console.log(`  ✓ Added next link to ${files[0]}: ${nextSlug}`);
          modified = true;
        } else if (currentNextMatch && currentNextMatch[1] !== nextSlug) {
          content = content.replace(/next:\s*"[^"]+"/m, `next: "${nextSlug}"`);
          console.log(`  ✓ Fixed next link in ${files[0]}: ${nextSlug}`);
          modified = true;
        }
      } else if (hasNextLink) {
        // Remove next link if target guide doesn't exist
        content = content.replace(/\s*next:\s*"[^"]+"\n/m, '');
        console.log(`  ✓ Removed next link to non-existent guide from ${files[0]}`);
        modified = true;
      }
    } else if (hasNextLink) {
      // Remove next link if this is now the last part
      content = content.replace(/\s*next:\s*"[^"]+"\n/m, '');
      console.log(`  ✓ Removed incorrect next link from ${files[0]}`);
      modified = true;
    }

    if (modified) {
      fs.writeFileSync(filePath, content);
    }
  });
}

// Main function
async function main() {
  try {
    console.log('Starting guide generation...');

    // Check for API key
    if (!process.env.NVIDIA_API_KEY) {
      throw new Error('NVIDIA_API_KEY environment variable is not set');
    }

    // Load topics
    const { topics, generatedTopics } = loadTopics();
    console.log(`Loaded ${topics.length} topics, ${generatedTopics.length} already generated`);

    // Select topic
    const topic = selectNextTopic(topics, generatedTopics);
    console.log(`Selected topic: ${topic.title} (${topic.difficulty})`);

    // Generate content
    console.log('Generating content with NVIDIA API...');
    const content = await generateGuideContent(topic);

    // Wait a moment before image generation to avoid rate limiting
    console.log('Waiting 5 seconds before image generation...');
    await new Promise(resolve => setTimeout(resolve, 5000));

    // Fetch image
    console.log('Fetching image...');
    const imageData = await fetchAndSaveImage(topic);

    // Create guide file
    const filename = await createGuideFile(topic, content, imageData);

    // Update series navigation in adjacent guides
    updateSeriesNavigation(topic);

    // Update generated topics
    if (!generatedTopics.includes(topic.title)) {
      generatedTopics.push(topic.title);
      saveGeneratedTopics(generatedTopics);
    }

    console.log('Guide generation complete!');
    console.log(`Total guides generated: ${generatedTopics.length}/${topics.length}`);

  } catch (error) {
    console.error('Error generating guide:', error.message || error);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  main();
}

module.exports = { main };
